name = "manfu"
compatibility_date = "2026-05-19"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "manfu-db"
database_id = "755de2a1-4176-4719-8af3-678a70c6edd8"

[vars]
APP_NAME = "慢富"
