name = "manfu"
compatibility_date = "2026-05-19"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "manfu-db"
database_id = "replace-with-cloudflare-d1-database-id"

[vars]
APP_NAME = "慢富"
